server:
  port: 18080

spring:
  application:
    name: woorim
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # TODO: hikari: jdbc-url ?????
    url: jdbc:mariadb://localhost:13306/woorim
    username: woorim_svc
    password: woorim_svc
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20